**delay**

延迟开始发送元素

**delayWhen**

延迟发送每一个元素, 但是需要传入一个cb，并且回传一个Observable，参数x就是传入的值，在cb中如果不用到x不会进行每一个延迟，只会延迟第一个开始的元素输出
~~~
var source = Rx.Observable.interval(300).take(5)
var example = source
              .delayWhen(
                x => Rx.Observable.empty().delay(100 * x * x)
              )
example.subscribe({
  next: (value) => { console.log(value); },
    error: (err) => { console.log('Error: ' + err); },
    complete: () => { console.log('complete'); }
})
~~~
**debounce**

用来处理高频触发，例如请求， Rx有debounce和debounceTime两个方法，前者传入Observable，后者传入毫秒
~~~
var source = Rx.Observable.interval(300).take(5)
var example = source.debounceTime(1000)

example.subscribe({
  next: (value) => { console.log(value); },
    error: (err) => { console.log('Error: ' + err); },
    complete: () => { console.log('complete'); }
})
// 4
// complete
-----------------
source:  --0--1--2--3--4|
        debounceTime(1000)
example: --------------4|
~~~

**throttle**

与debounce一样有throttle和 throttleTime两个方法。用于ui运算，比如高频事件

~~~
var source = Rx.Observable.interval(300).take(5);
var example = source.throttleTime(1000);

example.subscribe({
    next: (value) => { console.log(value); },
    error: (err) => { console.log('Error: ' + err); },
    complete: () => { console.log('complete'); }
});
// 0
// 4
// complete
~~~

**distinct**

去重

~~~
var source = Rx.Observable.from(['a','b','c','a','b'])

var example = source.distinct()

source : --a--b--c--a--b|
            distinct()
example: --a--b--c------|
~~~

此外，还可以给它传入select cb
~~~
var source = Rx.Observable.from([{ value: 'a'}, { value: 'b' }, { value: 'c' }, { value: 'a' }, { value: 'c' }])
            .zip(Rx.Observable.interval(300), (x, y) => x);
var example = source.distinct((x) => {
    return x.value
});

example.subscribe({
    next: (value) => { console.log(value); },
    error: (err) => { console.log('Error: ' + err); },
    complete: () => { console.log('complete'); }
});
// {value: "a"}
// {value: "b"}
// {value: "c"}
// complete
~~~

**distinctUntilChanged**

distinctUntilChanged和distinct一样会把相同的元素过滤掉，但是之和最后一次发出的元素相比

~~~
var  source = Rx.Observable.from(['a','b','c','c','b'])
var example = source.distinctUtilChanged()

source : --a--b--c--c--b|
            distinctUntilChanged()
example: --a--b--c-----b|
~~~

**catch**

catch是很常见的非同步错误处理方法，在Rxjs中也能够直接用catch来处理错误，在Rxjs中的catch可以回传一个Observable来送出新的值，让我们直接来看范例

~~~
var source = Rx.Observable.from(['a','b','c','b','d',2])

var example = source
              .map(x => x.toUpperCase())
              .catch(error => Rx.Observable.of('h'))


source : ----a----b----c----d----2|
        map(x => x.toUpperCase())
         ----a----b----c----d----X|
        catch(error => Rx.Observable.of('h'))
example: ----a----b----c----d----h|
~~~
由于2并没有toUpperCase()的方法，所以catch会捕捉到error而输出h

我们也可以在catch中直接回传一个Observable.empty()让它直接结束

同时，catch还接受第二个参数（obs），如果在catch回传一个obs，那么就相当于是重新执行当前Observable，无线循环

~~~
var source = Rx.Observable.from(['a','b','c','d',2])
            .zip(Rx.Observable.interval(500), (x,y) => x);

var example = source
                .map(x => x.toUpperCase())
                .catch((error, obs) => obs);

example.subscribe({
    next: (value) => { console.log(value); },
    error: (err) => { console.log('Error: ' + err); },
    complete: () => { console.log('complete'); }
});

source : ----a----b----c----d----2|
        map(x => x.toUpperCase())
         ----a----b----c----d----X|
        catch((error, obs) => obs)
example: ----a----b----c----d--------a----b----c----d--..
~~~

**retry()**

retry也可以在出错的时候重复执行，并且可以设置重复的次数
~~~
var source = Rx.Observable.from(['a','b','c','d',2])
            .zip(Rx.Observable.interval(500), (x,y) => x);

var example = source
                .map(x => x.toUpperCase())
                .retry(1);

example.subscribe({
    next: (value) => { console.log(value); },
    error: (err) => { console.log('Error: ' + err); },
    complete: () => { console.log('complete'); }
});
// a
// b
// c
// d
// a
// b
// c
// d
// Error: TypeError: x.toUpperCase is not a function

~~~

**retryWhen**

这里retryWhen会传入一个cb，cb中有一个参数传入一个Observable，但是这个Observable不是原来的Observable，而是一个errObs，我们可以对这个errObse进行操作，等它完成之后才会重新订阅原来的Observable。
~~~
source : ----a----b----c----d----2|
        map(x => x.toUpperCase())
         ----a----b----c----d----X|
        retryWhen(errorObs => errorObs.delay(1000))
example: ----a----b----c----d-------------------a----b----c----d----...
~~~

retryWhen通常不是用来做重新订阅的延迟，延迟通常用catch来做，retryWthen通常是用来做例外的错误的通知

~~~
var source = Rx.Observable.from(['a', 'b', 'c', 'd', 2])
var example = source
              .map(x => x.toUpperCase())
              .retryWhen(
                errorObs => error.Obs.map(err => fetch('...') )
              )
~~~

**repeat**

我们有时候可能会想要retry一只重复订阅的效果，但是没有错误发生，也就是说在没有错误发生的条件下，重复订阅，这时就可以用repeat来做到这件事情。用法基本和retury一样
~~~
var source = Rx.Observable.from(['a', 'b', 'c']).zip(Rx.Observable.interval(500), (x, y) => x)

var example = source.repeat(1)
source : ----a----b----c|
            repeat(1)
example: ----a----b----c----a----b----c|
~~~

错误处理的小范例
~~~
const title = document.getElementById('title')
var source = Rx.Observable.from(['a', 'b', 'c', 'd', 2])
.zip(Rx.Observable.interval(500), (x, y) => x)
.map(x => x.toUpperCase())

var example = source.catch((error, obs) => Rx.Observable.empty()
  .startWith('连线发生错误： 5秒后重连')
  .catch(obs.delay(5000))
)
~~~

